name: new version detector

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/new_version_detector.yml
  schedule:
    - cron: "23 6 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: new-version-detector
  cancel-in-progress: false

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  detect:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@2026.09.28.1

      - name: Set up git
        id: git_setup
        uses: Homebrew/actions/git-user-config@2026.09.28.1

      - name: Bump formulae
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GIT_COMMITTER_NAME: ${{ steps.git_setup.outputs.name }}
          HOMEBREW_GIT_COMMITTER_EMAIL: ${{ steps.git_setup.outputs.email }}
          TAP_NAME: ${{ steps.set-up-homebrew.outputs.tap-name }}
        run: brew bump --no-fork --open-pr --formulae --bump-synced --tap="$TAP_NAME"
